### ISSUE TITLE
Maintain mod Colonize Unlimited

### ISSUE THREAD

**Issue by satyrlord** [StellarisPlus/stellarisplus#2]
Colonize Unlimited

- Steam ID: 682582076
- Authors: @dosaki and @Thomahawk2k

- [x] Integrate Mod
- [x] Integration Testing
- [x] Balance Testing

**Comment by satyrlord** [comment]
@Majber please test Integration and Balance for this. Thank you.

**Comment by Majber** [comment]
Fast feedback:
1. Some visual bugs (planet icon is not entire visible): http://imgur.com/a/QA2wN
2. Balance: for my taste too much resources in the systems, link from above
3. Error log: http://pastebin.com/XJ0EcsrD

My personal opinion is that I dont rly like that mod becouse if I can be able to colonise every god damm rock it will create huge mess in late game, possible lags, too much micro and basicly M&T just in stellaris.

**Comment by satyrlord** [comment]
@Majber once @dosaki gets access to the repo perhaps he can fix some of your issues, however colonizing every goddamn rock makes a lot of sense in a videogame in which you can rule ringworlds and create massive fleets. However, I understand and fully sympathize with your worries, that's why we have the alternate version of the mod maintaned by @SerPercy without Colonize Unlimited

**Comment by dosaki** [comment]
1. I think @satyrlord already fixed that? But I'll fix the issue in the original mod and bring it over as well.

2. The resources were put there on purpose to rebalance terraforming in a more realistic way.
I guess one could make it optional, but I'll have to see if it's possible (from the new game parameters screen or something).

3. I can't see anything in the error log that has to do with Colonize Unlimited.

**Comment by satyrlord** [comment]
1. I fixed that.
2. Can we remove some of the resources? I love the extra resources because it allows more vertical development and playing tall but some people disagree.
3. I cleared the entire error log.

**Comment by dosaki** [comment]
The new resources are to make terraforming more realistic though. I don't think we should remove some of them, but we should probably have a toggle in the Galaxy Generation for Vanilla vs CU resources.

Not entirely sure if that is possible though.

**Comment by dosaki** [comment]
We should move this discussion to #5 and close this issue.
